name: jgomper_dcanfue_p2
description: Práctica Fase 2 - Lista dinámica
publish_to: 'none'

environment:
  sdk: '^3.9.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.3
  faker: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/fotocolonia.jpg
    - assets/images/l-homme-intense-prada.jpg
    - assets/images/luna-rossa-carbon.jpg
    - assets/images/sauvage-recharge-eau-de-toilette.jpg
    - assets/images/boss-bottled-parfum.jpg


